name: headlinr-android-build

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Prod
      APP_VERSION_NAME:
        description: 'App version name'
        required: true
      APP_VERSION_CODE:
        description: 'App version code'
        required: true

jobs:
  build:
    runs-on: macos-latest

    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEYSTORE_FILE: my-release-key.keystore
      ENV: ${{ github.event.inputs.ENV }}
      APP_VERSION_NAME: ${{ github.event.inputs.APP_VERSION_NAME }}
      APP_VERSION_CODE: ${{ github.event.inputs.APP_VERSION_CODE }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'

    - name: Create .env from secret
      run: echo "${{ secrets.DOTENV }}" > .env
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Decode keystore from secret
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore

    - name: Set versionCode and versionName
      run: |
        GRADLE_FILE=android/app/build.gradle.kts
        sed -i '' -E "s/versionName \".*\"/versionName \"$APP_VERSION_NAME\"/" $GRADLE_FILE
        sed -i '' -E "s/versionCode [0-9]+/versionCode $APP_VERSION_CODE/" $GRADLE_FILE
        grep 'versionName\|versionCode' $GRADLE_FILE
        
    - name: Create local.properties for Android and Flutter
      run: |
        echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
        echo "flutter.buildMode=release" >> android/local.properties
        echo "flutter.versionName=1.0.0" >> android/local.properties
        echo "flutter.versionCode=1" >> android/local.properties
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build signed APK
      run: |
        cd android
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$(pwd)/app/$ANDROID_KEYSTORE_FILE \
          -Pandroid.injected.signing.store.password=$ANDROID_KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$ANDROID_KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$ANDROID_KEY_PASSWORD
      
    - name: Rename APK file
      run: |
        mv build/app/outputs/apk/release/app-release.apk \
           "build/app/outputs/apk/release/${APP_VERSION_NAME}(${APP_VERSION_CODE}).apk"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/apk/release/${{ github.event.inputs.APP_VERSION_NAME }}(${{ github.event.inputs.APP_VERSION_CODE }}).apk
        
